### ISSUE TITLE
Variable guide lengths and paired-end data

### ISSUE THREAD

**Issue by sigven** [fulcrumgenomics/guide-counter#13]
Hi,

Thanks for developing this tool, results look pretty convincing. I was curious to see how your tool would perform on my dataset (compared to `mageck count`), but I seem to run into a very simple error at first: my guides are not of even length (fairly balanced distribution between 17bp and 20bp). Do you have any plans for supporting such scenarios? And is there any plans to add support for paired-end sequencing data (R1 + R2)? 

kind regards,
Sigve

**Comment by tfenne** [comment]
Hi @sigven.  I'm sorry - I have no near term plans to add support for either variable length guides or PE data.

**Comment by sigven** [comment]
Ok, thanks for the notice👍
